
services:
  prestamoapi:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: prestamoapi-docker
    container_name: prestamoapi
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "5000:3000"
    # working_dir: /var/www/prestamoapi
    #environment:
      #MONGODB: ${MONGODB}
      #PORT: ${PORT}
      #DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/prestamoapi

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: prestamo.master.api**
      POSTGRES_DB: prestamodb
    container_name: presmatodbserver
    volumes:
      - ./postgres:/var/lib/postgresql/data